package com.silverline.task.coursecontent.model;

import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

// ✅ MAKE SURE THIS IS THE IMPORT (NOT java.security.AuthProvider)
import com.silverline.task.coursecontent.model.AuthProvider;

import static org.junit.jupiter.api.Assertions.*;

class ModelTest {

    @Test
    void testUser() {
        User user = new User();
        user.setId(1L);
        user.setEmail("test@test.com");
        user.setPassword("pass");
        user.setRole("USER");
        user.setAuthProvider(AuthProvider.GOOGLE);
        user.setProfilePicture("pic.jpg");
        user.setName("John");

        assertEquals(1L, user.getId());
        assertEquals("test@test.com", user.getEmail());
        assertEquals("pass", user.getPassword());
        assertEquals("USER", user.getRole());
        assertEquals(AuthProvider.GOOGLE, user.getAuthProvider());
        assertEquals("pic.jpg", user.getProfilePicture());
        assertEquals("John", user.getName());

        // Test UserDetails methods (Required for Security coverage)
        assertTrue(user.isAccountNonExpired());
        assertTrue(user.isAccountNonLocked());
        assertTrue(user.isCredentialsNonExpired());
        assertTrue(user.isEnabled());
        assertEquals("test@test.com", user.getUsername());
        assertNotNull(user.getAuthorities());

        // Test Lombok generated methods (equals, hashCode, toString)
        User user2 = new User();
        user2.setId(1L);
        user2.setEmail("test@test.com");
        user2.setPassword("pass");
        user2.setRole("USER");
        user2.setAuthProvider(AuthProvider.GOOGLE);
        user2.setProfilePicture("pic.jpg");
        user2.setName("John");

        assertEquals(user, user2); // equals()
        assertEquals(user.hashCode(), user2.hashCode()); // hashCode()
        assertNotNull(user.toString()); // toString()
    }

    @Test
    void testNotification() {
        Notification n = new Notification();
        n.setId(1L);
        n.setMessage("Hello");
        n.setRead(true);
        n.setCreatedAt(LocalDateTime.now());
        n.setType(NotificationType.LIKE);

        User u = new User();
        n.setRecipient(u);
        n.setActor(u);

        CourseContent c = new CourseContent();
        n.setContent(c);

        assertEquals(1L, n.getId());
        assertEquals("Hello", n.getMessage());
        assertTrue(n.isRead());
        assertNotNull(n.getCreatedAt());
        assertEquals(NotificationType.LIKE, n.getType());
        assertEquals(u, n.getRecipient());
        assertEquals(u, n.getActor());
        assertEquals(c, n.getContent());
    }

    @Test
    void testCourseContent() {
        CourseContent c = new CourseContent();
        c.setId(10L);
        c.setFileName("file.pdf");
        c.setDescription("desc");
        c.setFileType("pdf");
        c.setFileSize(100L);
        c.setUploadDate(LocalDateTime.now());
        c.setFileUrl("http://url");
        c.setSummary("sum");
        c.setKeyPoints("keys");

        User u = new User();
        c.setUser(u);

        Set<User> likes = new HashSet<>();
        c.setLikes(likes);

        Set<Comment> comments = new HashSet<>();
        c.setComments(comments);

        Set<Notification> notifications = new HashSet<>();
        c.setNotifications(notifications);

        assertEquals(10L, c.getId());
        assertEquals("file.pdf", c.getFileName());
        assertEquals("desc", c.getDescription());
        assertEquals("pdf", c.getFileType());
        assertEquals(100L, c.getFileSize());
        assertNotNull(c.getUploadDate());
        assertEquals("http://url", c.getFileUrl());
        assertEquals("sum", c.getSummary());
        assertEquals("keys", c.getKeyPoints());
        assertEquals(u, c.getUser());
        assertEquals(likes, c.getLikes());
        assertEquals(comments, c.getComments());
        assertEquals(notifications, c.getNotifications());
    }

    @Test
    void testComment() {
        Comment c = new Comment();
        c.setId(5L);
        c.setText("Nice");
        c.setCreatedAt(LocalDateTime.now());

        User u = new User();
        c.setUser(u);

        CourseContent cc = new CourseContent();
        c.setCourseContent(cc);

        assertEquals(5L, c.getId());
        assertEquals("Nice", c.getText());
        assertNotNull(c.getCreatedAt());
        assertEquals(u, c.getUser());
        assertEquals(cc, c.getCourseContent());

        // Test AllArgsConstructor generated by Lombok
        Comment c2 = new Comment(1L, "Text", LocalDateTime.now(), u, cc);
        assertNotNull(c2);
    }

    @Test
    void testEnums() {
        // Enums need valueOf() calls to reach 100% coverage
        assertEquals(NotificationType.LIKE, NotificationType.valueOf("LIKE"));
        assertEquals(NotificationType.COMMENT, NotificationType.valueOf("COMMENT"));

        assertEquals(AuthProvider.LOCAL, AuthProvider.valueOf("LOCAL"));
        assertEquals(AuthProvider.GOOGLE, AuthProvider.valueOf("GOOGLE"));
    }
}